---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by panghuhu.
--- DateTime: 2022/7/8 11:00
---

-- 初始化耗时的模块
--local redis = require("resty.redis")
--local cjson = require("cjson")

-- 全局变量，不推荐
uuid_seed = ngx.time() + ngx.worker.pid()
-- 共享全局内存
local shared_data = ngx.shared.shared_data
shared_data:set("uuid_seed", uuid_seed)
