---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by panghuhu.
--- DateTime: 2022/7/6 10:29
---

local req = require("common.req")
local resp = require("common.resp")
local redis = require("common.redis")
local settings = require("common.systemSettings")

local _M = {}
function _M.authenticate()
    if not req or not req['authenticate'] then
        ngx.say(resp.fail(500, "无效token"))
        return nil;
    end

    local red = redis:new()
    local authenticate = req['authenticate']
    local token = settings.TOKEN_PREFIX .. authenticate
    --校验token是否存在 不存在或者过期均视为不可访问接口
    local res = red:exist(token)
    if res == 1 then
        ngx.log(ngx.INFO, "token:" .. token .. "校验通过")
        --重新刷新过期时间 10分钟
        local re = red:expire(token, settings.TOKEN_EXPIRE);
        if re == 0 then
            ngx.log(ngx.ERR, "redis:expire指令未生效,token:" .. token)
            return nil;
        end
        return authenticate
    elseif res == 0 then
        ngx.say(resp.fail(500, "token已失效，请重新登录..."))
        return nil;
    end
end

return _M;







