---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by panghuhu.
--- DateTime: 2022/6/25 15:42
---

local cjson = require "cjson"
local redis = require "common.redis"
local uuid = require "common.uuid"

uuid.randomseed(os.time()*10000)

-- 下面的代码跟官方给的基本类似，只是简化了初始化代码，已经关闭的细节，我记得网上看到过一个  是修改官网的代码实现，我不太喜欢修改库的源码，除非万不得已，所以尽量简单的实现
local red = redis:new()
--local ans, err = red:set("users", cjson.encode(users))
--if not ans then
--    ngx.say("failed to run sort: ", err)
--    return
--end


local uuid1 = uuid()
local user1 = {
    id = uuid1,
    username = "林晓林",
    account = "linxl",
    password = "e19d5cd5af0378da05f63f891c7467af",
    role = 1
}

local uuid2 = uuid()
local user2 = {
    id = uuid1,
    username = "刘寅",
    account = "liuyin",
    password = "e19d5cd5af0378da05f63f891c7467af",
    role = 2
}

local userlist = {}

userlist[uuid1] = cjson.encode(user1);
userlist[uuid2] = cjson.encode(user2);

local res, err = red:hmset("userlist", userlist)
if not res then
    ngx.log(ngx.ERR, "设置userlist失败！原因：" .. err)
end
red:close()


