---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by panghuhu.
--- DateTime: 2022/6/25 10:57
---

local uuid = require("common.jit-uuid")
uuid.seed()
local uuid1 = uuid()
local uuid2 = uuid()
ngx.log(ngx.INFO, "here's a new uuid1: " .. uuid1)
ngx.log(ngx.INFO, "here's a new uuid2: " .. uuid2)
ngx.say("here's a new uuid: ",uuid1)
ngx.say("here's a new uuid: ",uuid2)