---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by panghuhu.
--- DateTime: 2022/7/6 10:31
---

local json = require("cjson")

local _M = {}

function _M.success(data, msg)
    if not msg then
        msg = ""
    end
    if not data then
        data = ""
    end
    return json.encode({
        code = 200,
        msg = msg,
        data = data
    })
end

function _M.fail(code, msg, data)
    if not code then
        code = 500
    end
    if not msg then
        msg = ""
    end
    if not data then
        data = ""
    end
    return json.encode({
        code = code,
        msg = msg,
        data = data
    })
end


return _M
