---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by panghuhu.
--- DateTime: 2022/7/6 14:12
---

local _M = {}

_M.TOKEN_EXPIRE = 600 --token默认过期时间 10分钟
_M.TOKEN_PREFIX = "jnsec.network_encryption" --所有token相关的key的前缀

return _M;